package runner

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/nazaire/fleet/internal/config"
)

type LaunchResult struct {
	Agent   string
	Success bool
	Error   error
}

// CreateSessions creates tmux sessions and launches Claude Code in each.
// Returns immediately — does NOT wait for Claude to boot.
func CreateSessions(cfg *config.FleetConfig) []LaunchResult {
	var results []LaunchResult

	claudeCmd := "claude"
	for _, f := range cfg.Claude.Flags {
		claudeCmd += " " + f
	}

	for _, agent := range cfg.Agents {
		res := LaunchResult{Agent: agent.Name}

		if HasSession(agent.Name) {
			fmt.Printf("  ✓ %s already running, skipping\n", SessionName(agent.Name))
			res.Success = true
			results = append(results, res)
			continue
		}

		if err := CreateSession(agent.Name, cfg.Project.Cwd); err != nil {
			res.Error = fmt.Errorf("tmux create failed: %w", err)
			results = append(results, res)
			continue
		}

		if err := SendKeys(agent.Name, claudeCmd); err != nil {
			res.Error = fmt.Errorf("claude launch failed: %w", err)
			results = append(results, res)
			continue
		}

		res.Success = true
		results = append(results, res)
	}

	return results
}

// ConfigureAgentsAsync writes a shell script that waits for Claude prompts
// and sends init commands, then launches it in the background.
// Fleet exits immediately, the script runs independently.
func ConfigureAgentsAsync(cfg *config.FleetConfig) {
	scriptPath := fmt.Sprintf("%s/.fleet/configure-agents.sh", os.Getenv("HOME"))

	var script string
	script += "#!/bin/bash\n"
	script += "# Auto-generated by fleet — configures agents after Claude boots\n"
	script += "wait_prompt() {\n"
	script += "  local session=$1 timeout=$2 elapsed=0\n"
	script += "  while [ $elapsed -lt $timeout ]; do\n"
	script += "    if tmux capture-pane -t \"$session\" -p 2>/dev/null | grep -q '❯'; then\n"
	script += "      return 0\n"
	script += "    fi\n"
	script += "    sleep 1\n"
	script += "    elapsed=$((elapsed + 1))\n"
	script += "  done\n"
	script += "  return 1\n"
	script += "}\n\n"

	for _, agent := range cfg.Agents {
		session := SessionName(agent.Name)
		// Escape single quotes in role for bash
		escapedRole := strings.ReplaceAll(agent.Role, "'", "'\\''")

		script += fmt.Sprintf("# Configure %s\n", agent.Name)
		script += fmt.Sprintf("if wait_prompt %s 60; then\n", session)
		script += fmt.Sprintf("  tmux send-keys -t %s '/rename %s' Enter\n", session, agent.Name)
		script += fmt.Sprintf("  sleep 2\n")
		script += fmt.Sprintf("  tmux send-keys -t %s '/color %s' Enter\n", session, agent.Color)
		script += fmt.Sprintf("  sleep 2\n")

		registerCmd := fmt.Sprintf("/relay register %s %s %s", agent.Name, cfg.Project.Name, escapedRole)
		if agent.ReportsTo != "" {
			registerCmd += " Reports to " + agent.ReportsTo + "."
		}
		script += fmt.Sprintf("  tmux send-keys -t %s '%s' Enter\n", session, strings.ReplaceAll(registerCmd, "'", "'\\''"))
		script += fmt.Sprintf("  sleep 3\n")

		if !agent.IsExecutive {
			script += fmt.Sprintf("  wait_prompt %s 15\n", session)
			script += fmt.Sprintf("  tmux send-keys -t %s '/relay talk' Enter\n", session)
		}
		script += fmt.Sprintf("  echo '  ✓ %s configured'\n", session)
		script += "else\n"
		script += fmt.Sprintf("  echo '  ⚠ %s: timeout'\n", session)
		script += "fi\n\n"
	}

	os.WriteFile(scriptPath, []byte(script), 0755)

	// Launch in background — detached from fleet process
	cmd := exec.Command("bash", scriptPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Start()
	// Don't wait — fleet exits, script continues
}

// ConfigureAgents waits for Claude to boot and sends /rename, /color, /relay register.
// Synchronous version — blocks until all agents are configured.
func ConfigureAgents(cfg *config.FleetConfig) {
	fmt.Println("  ⏳ Waiting for Claude Code to initialize...")
	for _, agent := range cfg.Agents {
		if !HasSession(agent.Name) {
			continue
		}
		if err := WaitForPrompt(agent.Name, 60*time.Second); err != nil {
			fmt.Printf("  ⚠ %s: timeout waiting for prompt\n", agent.Name)
			continue
		}

		SendKeys(agent.Name, "/rename "+agent.Name)
		WaitForPrompt(agent.Name, 10*time.Second)

		SendKeys(agent.Name, "/color "+agent.Color)
		WaitForPrompt(agent.Name, 10*time.Second)

		registerCmd := fmt.Sprintf("/relay register %s %s %s",
			agent.Name, cfg.Project.Name, agent.Role)
		if agent.ReportsTo != "" {
			registerCmd += " Reports to " + agent.ReportsTo + "."
		}
		SendKeys(agent.Name, registerCmd)
		WaitForPrompt(agent.Name, 15*time.Second)

		if !agent.IsExecutive {
			SendKeys(agent.Name, "/relay talk")
		}

		fmt.Printf("  ✓ %s configured\n", SessionName(agent.Name))
	}
}
